import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { dehydrate, QueryClient, useQuery } from '@tanstack/react-query'
import { fetchPosts } from '@/hooks'
import Table from '../components/Table'
import Draggable from 'react-draggable';

// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { isLoading, error, data } = useQuery<unknown, Error>(["posts"], () =>
  fetchPosts(10)
);

  if (isLoading) return <div>Loading</div>;
  if (error) return "An error has occurred: " + error?.message;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Table/>
        <style jsx>{`
          p {
            color: red;
          }
        `}</style>
      </main>
    </>
  )
}



export async function getStaticProps() {
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery({
    queryKey: ['posts', 10],
    queryFn: () => fetchPosts(10),
  })

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

// export async function getServerSideProps() {
//   const queryClient = new QueryClient();

//   await queryClient.prefetchQuery("posts", () => fetchPosts(10));

//   return {
//     props: {
//       dehydratedState: dehydrate(queryClient),
//     },
//   };
// }