import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { dehydrate, QueryClient } from '@tanstack/react-query'
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>dawdawdwad</p>
        <style jsx>{`
          p {
            color: red;
          }
        `}</style>
      </main>
    </>
  )
}



// export async function getStaticProps() {
//   const queryClient = new QueryClient()

//   await queryClient.prefetchQuery({
//     queryKey: ['posts', 10],
//     queryFn: () => fetchPosts(10),
//   })

//   return {
//     props: {
//       dehydratedState: dehydrate(queryClient),
//     },
//   }
// }